---
- name: Remove host and volume
  hosts: localhost
  connection: local

  vars_files:
    - req1234.yml

  tasks:
  - name: Unmap volume
    dellemc_powerstore_volume:
      array_ip: "{{ target }}"
      user: "{{ user }}"
      password: "{{ password }}"
      verifycert: False
      vol_name: "{{ vol_name }}"
      host: "{{ host_name }}"
      mapping_state: "unmapped"
      state: "present"

  - name: Delete volume
    dellemc_powerstore_volume:
      array_ip: "{{ target }}"
      user: "{{ user }}"
      password: "{{ password }}"
      verifycert: False
      vol_name: "{{ vol_name }}"
      state: "absent"

  - name: Delete host
    dellemc_powerstore_host:
      array_ip: "{{ target }}"
      user: "{{ user }}"
      password: "{{ password }}"
      verifycert: False
      host_name: "{{ host_name }}"
      os_type: "{{ os_type }}"
      initiators: "{{ initiators }}"
      initiator_state: "absent-in-host"
      state: "absent"

